### ISSUE TITLE
Triphammer Feedback

### ISSUE THREAD

**Issue by Flaxbeard** [Flaxbeard/QuestionablyImmersive#12]
If you have any feedback on the new Triphammer for 1.14.4, whether visual, functional, or otherwise, please leave it here.

**Comment by WazWaz** [comment]
It seems to just crash Minecraft when I right-click with the Eng Hammer (IE 0.14-95, Forge 1.14.4-28.2.4):

`[21Apr2020 09:50:37.627] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindMethodException: java.lang.NoSuchMethodException: net.minecraft.item.BlockItem.getStateForPlacement(net.minecraft.item.BlockItemUseContext)
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findMethod(ObfuscationReflectionHelper.java:227) ~[?:?]
	at net.flaxbeard.questionablyimmersive.common.blocks.metal.TriphammerTileEntity.<init>(TriphammerTileEntity.java:88) ~[?:?]
`

**Comment by WazWaz** [comment]
Ouch, it also now seems that the Save is permanently broken - loading it up just crashes again with that same message. [But removing QI recovers it]
